Added build-nightly_13.yml Upgraded used GHA to the latest versions

diff --git a/.github/workflows/build-nightly_13.yml b/.github/workflows/build-nightly_13.yml
--- a/.github/workflows/build-nightly_13.yml
+++ b/.github/workflows/build-nightly_13.yml
@@ -1,10 +1,11 @@
-name: Build Nightly 12.3
-run-name: Version 12.3.${{ github.run_number }}
+name: Build Nightly 13
+run-name: Version 13.0.${{ github.run_number }}
 
 on:
   workflow_dispatch:
-  schedule:
-    - cron: '0 2 * * *'
+#TODO once V13 becomes develop: uncomment all lines commented out below
+#  schedule:
+#    - cron: '0 2 * * *'
 
 env:
   TARGET_FRAMEWORK: net8
@@ -14,32 +15,43 @@ permissions:
   packages: read
 
 jobs:
-  get-latest-commit-timespan:
-    runs-on: ubuntu-latest
-    outputs:
-      LATEST_COMMIT_TIMESPAN: ${{ steps.get-latest-commit-timespan.outputs.LATEST_COMMIT_TIMESPAN}}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v6
-        with:
-          fetch-depth: 0
+#  get-latest-commit-timespan:
+#    runs-on: ubuntu-latest
+#    outputs:
+#      LATEST_COMMIT_TIMESPAN: ${{ steps.get-latest-commit-timespan.outputs.LATEST_COMMIT_TIMESPAN}}
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v6
+#        with:
+#          fetch-depth: 0
+#
+#      - name: Get the previous commit timespan
+#        id: get-latest-commit-timespan
+#        shell: bash
+#        run: |
+#          commit=$(git log origin/develop -1 --format="%at")
+#          echo $commit
+#          now=$(date +%s)
+#          echo $now
+#          timespan=$[now - commit]
+#          echo "Timespan: ${timespan}"
+#          echo "LATEST_COMMIT_TIMESPAN=${timespan}" >> $GITHUB_ENV
+#          echo "LATEST_COMMIT_TIMESPAN=${timespan}" >> $GITHUB_OUTPUT
 
-      - name: Get the previous commit timespan
-        id: get-latest-commit-timespan
-        shell: bash
-        run: |
-          commit=$(git log origin/develop -1 --format="%at")
-          echo $commit
-          now=$(date +%s)
-          echo $now
-          timespan=$[now - commit]
-          echo "Timespan: ${timespan}"
-          echo "LATEST_COMMIT_TIMESPAN=${timespan}" >> $GITHUB_ENV
-          echo "LATEST_COMMIT_TIMESPAN=${timespan}" >> $GITHUB_OUTPUT
+  check-branch:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Validate source branch
+      run: |
+        if [ "${{ github.ref_name }}" != "V13" ]; then
+          echo "::error::Please call the workflow from the V13 branch"
+          exit 1
+        fi
 
   build-nightly:
-    needs: get-latest-commit-timespan
-    if: needs.get-latest-commit-timespan.outputs.LATEST_COMMIT_TIMESPAN < 86400
+    needs: check-branch #TODO remove once V13 become develop
+#    needs: get-latest-commit-timespan
+#    if: needs.get-latest-commit-timespan.outputs.LATEST_COMMIT_TIMESPAN < 86400
     runs-on: windows-latest
     steps:
       - name: Checkout code
@@ -54,7 +66,7 @@ jobs:
 
       - name: define env variables
         run: |
-          echo "APP_VERSION=12.3.${{ github.run_number }}" | Out-File -FilePath $env:GITHUB_ENV -Append
+          echo "APP_VERSION=13.0.${{ github.run_number }}" | Out-File -FilePath $env:GITHUB_ENV -Append
 
       - name: Build
         run: |
@@ -141,18 +153,18 @@ jobs:
           name: PKSim R Dependencies
           path: src\PKSimRDependencyResolution\bin\Debug\${{env.TARGET_FRAMEWORK}}\pk-sim-r-dependencies.zip
 
-  cleanup-job:
-    needs: get-latest-commit-timespan
-    if: needs.get-latest-commit-timespan.outputs.LATEST_COMMIT_TIMESPAN >= 86400
-    runs-on: ubuntu-latest
-    permissions:
-      actions: write
-    steps:
-      - name: Cancel workflow run
-        run: |
-          curl -L \
-            -X POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel"
+#  cleanup-job:
+#    needs: get-latest-commit-timespan
+#    if: needs.get-latest-commit-timespan.outputs.LATEST_COMMIT_TIMESPAN >= 86400
+#    runs-on: ubuntu-latest
+#    permissions:
+#      actions: write
+#    steps:
+#      - name: Cancel workflow run
+#        run: |
+#          curl -L \
+#            -X POST \
+#            -H "Accept: application/vnd.github+json" \
+#            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+#            -H "X-GitHub-Api-Version: 2022-11-28" \
+#            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel"
